In [53]:
import numpy as np
#import math

In [3]:
def f1(x,y):
    result = []
    if len(x) != len(y):
        raise ValueError("Vectors must be same length")
    for i, v in enumerate(x):
        result.append(x[i] + y[i])
    return result

In [4]:
x = np.array([1,2,3])
y = np.array([1,2,3])
z = x + y
print z

[2 4 6]


In [5]:
def f2(a,x):
    result = []
    for i,v in enumerate(x):
        result.append(a * v)
    return result

In [6]:
w = 5 * z
print w

[10 20 30]


In [7]:
def f3(x):
    result = []
    norm = 0.0
    for v in x:
        norm += v*v
    norm = math.sqrt(norm)
    for i,v in enumerate(x):
        result.append( x[i]/norm )
    return result

In [8]:
a = w/np.linalg.norm(w)
print a

[ 0.26726124  0.53452248  0.80178373]


In [9]:
def f4(x):
    norm = 0.0
    for v in x:
        norm += v*v
    norm = math.sqrt(norm)
    return norm

In [10]:
b = np.linalg.norm(w)
print b

37.4165738677


In [11]:
def f5(x):
    sigm = lambda x: (1.0 / (1.0 + math.exp(-x)))
    result = []
    for v in x:
        result.append(sigm(v))
    return result

In [12]:
f5(w)

[0.9999546021312976, 0.9999999979388463, 0.9999999999999065]

In [13]:
sigmoid = 1.0/(1.0 + np.exp(-w))
print sigmoid


[ 0.9999546  1.         1.       ]


In [14]:
def f6(m, nrows, ncols):
    for i in range(nrows):
        for j in range(ncols):
            if m[ncols * i + j] != m[ncols * j + i]:
                return False
    return True

In [15]:
f6([1,2,2,2,2,2],3,2)

True

In [56]:
x  = np.asarray([1,2,2,2,2,2])
(x.transpose() == x).all()

True

In [45]:
def f7(x,y):
    s = 0.0
    if len(x) != len(y):
        raise ValueError("lengths differ.")
    for i,v in enumerate(x):
        s += x[i] * y[i]
    return s

In [18]:
f7([1,2,3],[1,2,3])

14.0

In [57]:
x = np.array([1,2,3])
y = np.array([1,2,3])
z = np.dot(x,y)
print z

14


In [20]:
def f8(m, x, nrows, ncols):
    result = []
    if len(x) != ncols:
        raise ValueError("m and x have incompatible sizes.")
    for i, v in enumerate(x):
        result.append(f7(m[i * ncols : (i+1)*ncols], x))
    return result

In [21]:
f8([1,1,1,1], [1,1], 2, 2)

[2.0, 2.0]

In [22]:
x = np.array([[1,1], [1,1]])
y = np.array([1,1])
z = np.dot(x,y)
print z

[2 2]


In [23]:
import random
def f9(length):
    result = []
    if length <= 0:
        raise ValueError("Need a positive argument.")
    for i in range(length):
        result.append(random.gauss(0, 0.1))
    return result

In [41]:
j = np.random.normal(0,0.1,3)
print j

[ 0.0203335  -0.0466328   0.07043945]


In [25]:
def f10(x):
    if len(x) == 0:
        raise ValueError("need a nonempty x.")
    minval = x[0]
    for v in x:
        if v <= minval:
            minval = v
    return minval

In [60]:
np.min(w)

10

In [27]:
def f11(x):
    if len(x) == 0:
        raise ValueError("need nonempty x.")
    maxval = x[0]
    for v in x:
        if v >= maxval:
            maxval = v
    return maxval

In [61]:
np.max(w)

30